In [14]:
import numpy as np

In [15]:
a = np.array(5)
a

array(5)

In [16]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
a = a.reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)

(3, 5)
2
15
int64


In [20]:
b = np.arange(20)
b = b.reshape(2, 5, 2)
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [21]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
a = np.array([20, 30, 40, 50])
a

array([20, 30, 40, 50])

In [26]:
b = np.arange(4)
b

array([0, 1, 2, 3])

In [ ]:
a + b

array([20, 31, 42, 53])

In [30]:
c = a * b
c

array([  0,  30,  80, 150])

In [31]:
c > 50

array([False, False,  True,  True])